nodeLinker: node-modules

# Network reliability fixes for GitHub Actions
httpTimeout: 120000
httpRetry: 3
networkConcurrency: 8

# Skip problematic native builds in CI
supportedArchitectures:
  os: ["current"]
  cpu: ["current"]
