approvedGitRepositories:
  - "**"

enableScripts: true

httpRetry: 3

httpTimeout: 120000

networkConcurrency: 8

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - current
  os:
    - current
