CREATE TABLE "hellok8s_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hellok8s_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(256) NOT NULL,
	"slug" varchar(256) NOT NULL,
	"content" text NOT NULL,
	"created_by_id" varchar(255) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "hellok8s_post_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "hellok8s_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"first_name" varchar(255),
	"last_name" varchar(255),
	"email" varchar(255) NOT NULL,
	"password" varchar(255),
	"is_superuser" boolean DEFAULT false NOT NULL,
	"email_verified" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"image" varchar(255),
	CONSTRAINT "hellok8s_user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
ALTER TABLE "hellok8s_post" ADD CONSTRAINT "hellok8s_post_created_by_id_hellok8s_user_id_fk" FOREIGN KEY ("created_by_id") REFERENCES "public"."hellok8s_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "created_by_idx" ON "hellok8s_post" USING btree ("created_by_id");--> statement-breakpoint
CREATE INDEX "title_idx" ON "hellok8s_post" USING btree ("title");--> statement-breakpoint
CREATE INDEX "slug_idx" ON "hellok8s_post" USING btree ("slug");