CREATE TABLE "hellok8s_image" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hellok8s_image_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"file_name" varchar(255) NOT NULL,
	"original_path" varchar(512) NOT NULL,
	"transformed_path" varchar(512),
	"mime_type" varchar(100) NOT NULL,
	"file_size" integer NOT NULL,
	"width" integer,
	"height" integer,
	"uploaded_by_id" varchar(255) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "hellok8s_image" ADD CONSTRAINT "hellok8s_image_uploaded_by_id_hellok8s_user_id_fk" FOREIGN KEY ("uploaded_by_id") REFERENCES "public"."hellok8s_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "uploaded_by_idx" ON "hellok8s_image" USING btree ("uploaded_by_id");--> statement-breakpoint
CREATE INDEX "created_at_idx" ON "hellok8s_image" USING btree ("created_at");