apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-config
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    # NOTE: We want the configmaps to be created/updated before anything else
    "helm.sh/hook-weight": "-3"
data:
  NEXT_PUBLIC_CLIENTVAR: "{{ .Values.appConfig.clientVar }}"
  DATABASE_URL: "{{ .Values.appConfig.databaseUrl }}"
  REDIS_URL: "{{ .Values.appConfig.redisUrl }}"
  AUTH_SECRET: "{{ .Values.appConfig.authSecret }}"
